runtime: php74
env: standard

runtime_config:
  document_root: public
  skip_lockdown_document_root: true
env_variables:
  # Add any environment variables needed by your application
  CI_ENV: production
  MYSQL_USER: bug-reporter
  MYSQL_PASSWORD: AsbvTr14234Reder
  MYSQL_DATABASE: bugdb
  MYSQL_DSN: mysql:dbname=bugdb;unix_socket=/cloudsql/bug-reporter-management:europe-west1:bugdb
  


build_env_variables:
  GOOGLE_COMPOSER_VERSION: 2.1.9

