runtime: php74
env: standard

runtime_config:
  document_root: public

env_variables:
  # Add any environment variables needed by your application
  CI_ENV: production
  app.sessionSavePath: '/tmp/bug-reporter-management/ci4_session'


build_env_variables:
  GOOGLE_COMPOSER_VERSION: 2.1.9

