runtime: php74
env: standard

runtime_config:
  document_root: public

env_variables:
  # Add any environment variables needed by your application
  CI_ENV: production


build_env_variables:
  GOOGLE_COMPOSER_VERSION: 2.1.9

